### ISSUE TITLE
Regeneration links to random CI feedstocks.

### ISSUE THREAD

**Issue by pmlandwehr** [pmlandwehr/tick-feedstocks#14]
Each feedstock has a dedicated CI project. For unclear reasons, when regenerating the patched feedstocks `conda smithy` assigns the feedstock to new, randomly drawn CI projects. This should be corrected; it likely causes some unnecessary regeneration.

**Comment by jakirkham** [comment]
Could you please expand on this a bit more? An example might help as well.

**Comment by pmlandwehr** [comment]
So a simple example would be the last time I did an automated regeneration of `debtcollector`, which uses code poached from `regenerate_feedstock.py` (so `gitpython`).  After regeneration, the CircleCI build badge pointed to: https://circleci.com/gh/conda-forge/tmp0bnegy33-feedstock.svg

Once I did a manual regeneration, it was corrected to: https://circleci.com/gh/conda-forge/debtcollector-feedstock.svg

**Comment by jakirkham** [comment]
I see. Thanks for the info. Yeah I think regenerate/re-render use the directory name to fill those out. I'm guessing you are using a temporary directory, correct? Would suggest creating the actual feedstock directory within the temporary directory. That should fix the issue.

**Comment by pmlandwehr** [comment]
Definitely using a temporary directory, so that sounds like a good fix.

**Comment by pmlandwehr** [comment]
Fixed!
